title: Dumboria
author: Dr. Dumbor
email: 4eggs@bumboria.com
description: > # this means to ignore newlines until "baseurl:"
  Dumboria is a great place for the dumb people. It was imagined and created by
  Dr. Dumbor through his shower soap. We hope you're dumb enough to apply for citizenship for dumboria.

# social links
twitter_username: dumbordumb # DO NOT include the @ character, or else the build will fail!
github_username:  No Code because dr.dumbor is dumb # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
